# Generated by Django 5.1.3 on 2024-12-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adopters",
            fields=[
                (
                    "adopterID",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("phoneNumber", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Animals",
            fields=[
                ("animalID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("dateOfArrival", models.DateField()),
                ("adoptedOrNot", models.IntegerField()),
                ("healthStatus", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("locationID", models.IntegerField()),
                ("reasonForIntake", models.CharField(max_length=100)),
                ("adoptionFee", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Donors",
            fields=[
                ("donorID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phoneNumber", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ShelterLocations",
            fields=[
                ("locationID", models.AutoField(primary_key=True, serialize=False)),
                ("locationName", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phoneNumber", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("currentOccupancy", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staffID",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("phoneNumber", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("hireDate", models.DateField()),
                ("salary", models.IntegerField()),
                ("workLocation", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Donations",
            fields=[
                ("donationID", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("donationDate", models.DateField()),
                (
                    "donorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.donors",
                    ),
                ),
                (
                    "locationID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.shelterlocations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecords",
            fields=[
                ("medicalID", models.AutoField(primary_key=True, serialize=False)),
                ("diagnosis", models.CharField(max_length=200)),
                ("treatment", models.TextField()),
                ("date", models.DateField()),
                ("note", models.TextField()),
                (
                    "animalID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.animals",
                    ),
                ),
                (
                    "staffID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdoptionRequests",
            fields=[
                (
                    "adoptionID",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("dateAdopted", models.DateField()),
                ("adoptionStatus", models.CharField(max_length=100)),
                (
                    "adopterID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.adopters",
                    ),
                ),
                (
                    "animalID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.animals",
                    ),
                ),
                (
                    "staffAdministrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paycheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payDate", models.DateField()),
                ("hoursWorked", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "staffID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterapp.staff",
                    ),
                ),
            ],
            options={
                "unique_together": {("payDate", "staffID")},
            },
        ),
    ]
