# Generated by Django 5.1.3 on 2024-12-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelterapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donations",
            name="donorID",
        ),
        migrations.AddField(
            model_name="donations",
            name="address",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="donations",
            name="email",
            field=models.EmailField(default="N/A", max_length=254),
        ),
        migrations.AddField(
            model_name="donations",
            name="name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="donations",
            name="phoneNumber",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shelterlocations",
            name="funds",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Donors",
        ),
    ]
