# Generated by Django 5.1.3 on 2024-12-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='adoptionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='adoptionStatus',
            field=models.CharField(choices=[('not_viewed', 'Not Viewed'), ('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='not_viewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='dateAdopted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
