# Generated by Django 5.1.3 on 2024-12-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelterapp", "0002_remove_donations_donorid_donations_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donations",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="donations",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="donations",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="donations",
            name="phoneNumber",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="shelterlocations",
            name="funds",
            field=models.IntegerField(),
        ),
    ]
