# Generated by Django 5.1.3 on 2024-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0002_alter_adoptionrequest_adoptionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(),
        ),
    ]
